# Generated by Django 4.1.3 on 2024-03-19 12:17

import app_product.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Kênh bán hàng',
                'db_table': 'tb_channel',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_channel', to='app_product.channel')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'db_table': 'tb_product',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rate', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rate_product', to='app_product.product')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'db_table': 'tb_rate',
            },
        ),
        migrations.CreateModel(
            name='RateMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=app_product.models.rate_upload_to)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RateMedia_rate', to='app_product.rate')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'db_table': 'tb_rate_image',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=app_product.models.product_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductImage_product', to='app_product.product')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'db_table': 'tb_product_image',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('display_price', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Price_product', to='app_product.product')),
            ],
            options={
                'verbose_name': 'Giá bán',
                'db_table': 'tb_price',
            },
        ),
    ]
