# Generated by Django 4.1.3 on 2024-03-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratemedia',
            options={'verbose_name': 'Hình ảnh đánh giá'},
        ),
    ]
